create-messages-table=CREATE TABLE IF NOT EXISTS messages (id INTEGER IDENTITY PRIMARY KEY, author VARCHAR(255), date DATETIME, content CLOB)
get-last-messages=SELECT id, author, TO_CHAR(date, 'YYYY-MM-DD HH24:MI:SS') AS date, content FROM messages ORDER BY date DESC LIMIT 20
add-message=INSERT INTO messages (author, date, content) VALUES (?, NOW(), ?)
